/**
 * ch06.js -- Chapter 6: Master Budget and Responsibility Accounting
 * Tools: Operating Budget Builder, Sensitivity Analysis,
 *        Responsibility Center Classifier, Cash Budget, Kaizen Simulator
 */
import { markChapterComplete, isChapterComplete, resetChapter } from '/js/core/progress-tracker.js';
import { initRandomizer } from '/js/components/randomizer.js';
import { renderShowWork } from '/js/components/show-work.js';

// ── Shared state ──────────────────────────────────────────────
let budgetResults = null;

const fmt    = n => '$' + Math.round(n).toLocaleString();
const fmtDec = (n, d=2) => '$' + n.toFixed(d);
const fmtPct = n => (n * 100).toFixed(1) + '%';
const gv     = id => parseFloat(document.getElementById(id)?.value) || 0;
const gs     = id => document.getElementById(id)?.value || '';

function getOrCreate(id, tag, className, parent) {
  let el = document.getElementById(id);
  if (!el) {
    el = document.createElement(tag || 'div');
    el.id = id;
    if (className) el.className = className;
    if (parent) parent.appendChild(el);
  }
  return el;
}

// ── Data ──────────────────────────────────────────────────────

const RC_SCENARIOS = [
  {
    scenario: 'The maintenance department of a Marriott hotel. The manager is responsible only for the costs of maintaining the hotel -- not for revenues generated by the hotel.',
    answer: 'cost',
    explanation: 'A cost center manager is accountable for costs only. The maintenance manager controls costs but has no influence over hotel revenues.'
  },
  {
    scenario: 'The sales department of a Marriott hotel. The sales manager is responsible primarily for booking revenues -- room nights, events, and banquets.',
    answer: 'revenue',
    explanation: 'A revenue center manager is accountable for revenues only. The sales manager drives bookings but does not control the costs of running the hotel.'
  },
  {
    scenario: 'The general manager of a Marriott hotel location. This manager is accountable for both the revenues the hotel generates and all costs incurred to operate it.',
    answer: 'profit',
    explanation: 'A profit center manager is accountable for both revenues and costs. The hotel GM controls what the hotel charges and what it spends.'
  },
  {
    scenario: 'The regional vice president responsible for deciding how much to invest in new Marriott hotel projects and for the revenues and costs generated from those investments.',
    answer: 'investment',
    explanation: 'An investment center manager is accountable for investments, revenues, and costs. The regional VP decides capital allocation and is evaluated on return on investment.'
  },
  {
    scenario: 'OPD office products distributor: the sales department, where each salesperson receives a commission on revenues per order regardless of order size or delivery cost.',
    answer: 'revenue',
    explanation: 'When salespeople are evaluated only on revenues -- not on the costs of fulfilling orders -- the department is a revenue center. OPD later changed this to a profit center to align incentives.'
  },
  {
    scenario: 'A call center at a bank where managers are evaluated on cost per call handled and average handle time -- with no accountability for whether customers buy additional products.',
    answer: 'cost',
    explanation: 'When a call center is evaluated only on cost efficiency metrics, it is a cost center. The manager focuses on reducing costs per call, not on revenue generation.'
  },
  {
    scenario: 'The Ritz-Carlton Boston hotel. The general manager and controller are responsible for local revenue forecasts, standard costs, and the hotel\'s overall profitability.',
    answer: 'profit',
    explanation: 'The Ritz-Carlton example from the chapter opening -- each hotel location is a profit center. The GM is accountable for both revenues and costs at that location.'
  },
  {
    scenario: 'A division of a large corporation where the division manager decides how much capital equipment to purchase, sets prices, and manages all operating costs.',
    answer: 'investment',
    explanation: 'When a manager controls capital investment decisions in addition to revenues and costs, the unit is an investment center. Performance is typically measured by ROI or residual income.'
  },
  {
    scenario: 'The purchasing department of a manufacturer. The purchasing manager negotiates prices with suppliers and is evaluated on total purchase costs relative to budget.',
    answer: 'cost',
    explanation: 'The purchasing department is a cost center -- the manager is accountable for the costs of materials purchased. Even though market prices are partly outside the manager\'s control, accountability for costs motivates the manager to negotiate effectively.'
  },
  {
    scenario: 'Southwest Airlines fuel management group. This group is responsible for hedging fuel costs and managing the total fuel expense across the entire airline.',
    answer: 'cost',
    explanation: 'The fuel management group controls a major cost item -- fuel -- but does not set ticket prices or control revenues. It is a cost center evaluated on fuel cost per available seat mile.'
  },
];

const KEY_TERMS = [
  { term: 'Master Budget', definition: 'Expresses management\'s operating and financial plans for a specified period (usually a fiscal year) and includes a set of budgeted financial statements. It is the initial plan of what the company intends to accomplish in the period.' },
  { term: 'Operating Budget', definition: 'The budgeted income statement and its supporting budget schedules. The starting point is the revenues budget. Supporting schedules include production, direct materials, direct labor, manufacturing overhead, ending inventories, cost of goods sold, and operating costs.' },
  { term: 'Financial Budget', definition: 'The part of the master budget made up of the capital expenditures budget, the cash budget, the budgeted balance sheet, and the budgeted statement of cash flows.' },
  { term: 'Rolling Budget', definition: 'Also called a continuous budget or rolling forecast. A budget that is always available for a specified future period, created by continually adding a new period as the most recent period ends.' },
  { term: 'Activity-Based Budgeting (ABB)', definition: 'A budgeting method that focuses on the budgeted cost of the activities necessary to produce and sell products and services. Uses activity-based cost drivers rather than output-based drivers.' },
  { term: 'Responsibility Center', definition: 'A part, segment, or subunit of an organization whose manager is accountable for a specified set of activities. The four types are cost centers, revenue centers, profit centers, and investment centers.' },
  { term: 'Cost Center', definition: 'A responsibility center in which the manager is accountable for costs only. Example: a manufacturing department or maintenance department.' },
  { term: 'Revenue Center', definition: 'A responsibility center in which the manager is accountable for revenues only. Example: a sales department evaluated solely on bookings.' },
  { term: 'Profit Center', definition: 'A responsibility center in which the manager is accountable for both revenues and costs. Example: a hotel general manager responsible for the hotel\'s operating income.' },
  { term: 'Investment Center', definition: 'A responsibility center in which the manager is accountable for investments, revenues, and costs. Example: a division manager who decides on capital expenditures and is evaluated on return on investment.' },
  { term: 'Responsibility Accounting', definition: 'A system that measures the plans, budgets, actions, and actual results of each responsibility center. Associates financial items with managers on the basis of which manager has the most knowledge about specific items.' },
  { term: 'Controllability', definition: 'The degree of influence a specific manager has over costs, revenues, or related items for which he or she is responsible. A controllable cost is any cost primarily subject to the influence of a given responsibility center manager for a given period.' },
  { term: 'Budgetary Slack', definition: 'The practice of underestimating budgeted revenues or overestimating budgeted costs to make budgeted targets easier to achieve. Occurs when managers are evaluated against the budget they helped create.' },
  { term: 'Kaizen Budgeting', definition: 'A budgeting approach that explicitly incorporates continuous improvement anticipated during the budget period into the budget numbers. Kaizen is Japanese for continuous improvement.' },
  { term: 'Cash Budget', definition: 'A schedule of expected cash receipts and cash disbursements. Predicts the effects on the cash position at the given level of operations. Shows when borrowing is needed and when loans can be repaid.' },
  { term: 'Financial Planning Models', definition: 'Mathematical representations of the relationships among operating activities, financing activities, and other factors that affect the master budget. Enable sensitivity analysis.' },
  { term: 'Pro Forma Statements', definition: 'Another name for budgeted financial statements. Represents management\'s expectations of financial results before the period begins.' },
];

// ── Tool 1: Operating Budget Builder ─────────────────────────

function initBudgetBuilder() {
  const calcBtn   = document.getElementById('budget-calculate');
  const resultsEl = document.getElementById('budget-results');
  if (!calcBtn) return;

  calcBtn.addEventListener('click', () => buildBudget(resultsEl));

  initRandomizer('budget-randomize', [
    { id: 'b-p1-sales',    min: 10000,  max: 100000,  step: 5000,  integer: true },
    { id: 'b-p1-price',    min: 200,    max: 1000,    step: 50,    integer: true },
    { id: 'b-p1-end-inv',  min: 500,    max: 20000,   step: 500,   integer: true },
    { id: 'b-p2-sales',    min: 2000,   max: 30000,   step: 1000,  integer: true },
    { id: 'b-p2-price',    min: 400,    max: 2000,    step: 100,   integer: true },
    { id: 'b-p2-end-inv',  min: 100,    max: 5000,    step: 100,   integer: true },
    { id: 'b-m1-cost',     min: 3,      max: 20,      step: 1,     integer: true },
    { id: 'b-m2-cost',     min: 5,      max: 30,      step: 1,     integer: true },
    { id: 'b-dl-rate',     min: 15,     max: 40,      step: 1,     integer: true },
    { id: 'b-var-oh-rate', min: 10,     max: 40,      step: 1,     integer: true },
    { id: 'b-fix-oh',      min: 500000, max: 5000000, step: 100000,integer: true },
  ], () => buildBudget(resultsEl));
}

function buildBudget(resultsEl) {
  const p1Name    = gs('b-p1-name') || 'Product 1';
  const p2Name    = gs('b-p2-name') || 'Product 2';
  const m1Name    = gs('b-m1-name') || 'Material 1';
  const m2Name    = gs('b-m2-name') || 'Material 2';

  const p1Sales   = gv('b-p1-sales');
  const p1Price   = gv('b-p1-price');
  const p1EndInv  = gv('b-p1-end-inv');
  const p1BegInv  = gv('b-p1-beg-inv');
  const p1BegVal  = gv('b-p1-beg-inv-val');
  const p1DLHrs   = gv('b-p1-dl-hrs');
  const p1SetupHrs= gv('b-p1-setup-hrs');
  const p1CuFt    = gv('b-p1-cuft');

  const p2Sales   = gv('b-p2-sales');
  const p2Price   = gv('b-p2-price');
  const p2EndInv  = gv('b-p2-end-inv');
  const p2BegInv  = gv('b-p2-beg-inv');
  const p2BegVal  = gv('b-p2-beg-inv-val');
  const p2DLHrs   = gv('b-p2-dl-hrs');
  const p2SetupHrs= gv('b-p2-setup-hrs');
  const p2CuFt    = gv('b-p2-cuft');

  const m1Cost    = gv('b-m1-cost');
  const m1P1Qty   = gv('b-m1-p1-qty');
  const m1P2Qty   = gv('b-m1-p2-qty');
  const m1BegInv  = gv('b-m1-beg-inv');
  const m1EndInv  = gv('b-m1-end-inv');

  const m2Cost    = gv('b-m2-cost');
  const m2P1Qty   = gv('b-m2-p1-qty');
  const m2P2Qty   = gv('b-m2-p2-qty');
  const m2BegInv  = gv('b-m2-beg-inv');
  const m2EndInv  = gv('b-m2-end-inv');

  const dlRate    = gv('b-dl-rate');
  const varOHRate = gv('b-var-oh-rate');
  const fixOH     = gv('b-fix-oh');
  const varSetup  = gv('b-var-setup-rate');
  const fixSetup  = gv('b-fix-setup');

  const design    = gv('b-design');
  const mktPct    = gv('b-mkt-pct') / 100;
  const mktFix    = gv('b-mkt-fix');
  const distVar   = gv('b-dist-var');
  const distFix   = gv('b-dist-fix');

  // S1: Revenues
  const p1Rev    = p1Sales * p1Price;
  const p2Rev    = p2Sales * p2Price;
  const totalRev = p1Rev + p2Rev;

  // S2: Production
  const p1Prod   = p1Sales + p1EndInv - p1BegInv;
  const p2Prod   = p2Sales + p2EndInv - p2BegInv;

  // S3A: DM Usage
  const m1P1Use  = p1Prod * m1P1Qty;
  const m1P2Use  = p2Prod * m1P2Qty;
  const m1Total  = m1P1Use + m1P2Use;
  const m2P1Use  = p1Prod * m2P1Qty;
  const m2P2Use  = p2Prod * m2P2Qty;
  const m2Total  = m2P1Use + m2P2Use;

  const m1BegCost   = Math.min(m1BegInv, m1Total) * m1Cost;
  const m1NewCost   = Math.max(0, m1Total - m1BegInv) * m1Cost;
  const m1UsedCost  = m1BegCost + m1NewCost;
  const m2BegCost   = Math.min(m2BegInv, m2Total) * m2Cost;
  const m2NewCost   = Math.max(0, m2Total - m2BegInv) * m2Cost;
  const m2UsedCost  = m2BegCost + m2NewCost;
  const totalDMUsed = m1UsedCost + m2UsedCost;

  // S3B: DM Purchases
  const m1PurchaseQty = m1Total + m1EndInv - m1BegInv;
  const m2PurchaseQty = m2Total + m2EndInv - m2BegInv;
  const m1PurchaseCost= m1PurchaseQty * m1Cost;
  const m2PurchaseCost= m2PurchaseQty * m2Cost;

  // S4: DL
  const p1DLHrsTotal = p1Prod * p1DLHrs;
  const p2DLHrsTotal = p2Prod * p2DLHrs;
  const totalDLHrs   = p1DLHrsTotal + p2DLHrsTotal;
  const p1DLCost     = p1DLHrsTotal * dlRate;
  const p2DLCost     = p2DLHrsTotal * dlRate;
  const totalDLCost  = p1DLCost + p2DLCost;

  // S5: Overhead
  const totalVarOH   = varOHRate * totalDLHrs;
  const totalOpsOH   = totalVarOH + fixOH;
  const p1SetupTotal = p1Prod * p1SetupHrs;
  const p2SetupTotal = p2Prod * p2SetupHrs;
  const totalSetupHrs= p1SetupTotal + p2SetupTotal;
  const totalVarSetup= varSetup * totalSetupHrs;
  const totalSetupOH = totalVarSetup + fixSetup;
  const totalOH      = totalOpsOH + totalSetupOH;

  // OH rates
  const opsOHRate    = totalDLHrs   > 0 ? totalOpsOH  / totalDLHrs   : 0;
  const setupOHRate  = totalSetupHrs > 0 ? totalSetupOH / totalSetupHrs : 0;

  // S6: Unit costs
  const p1M1Cost     = m1P1Qty * m1Cost;
  const p1M2Cost     = m2P1Qty * m2Cost;
  const p1DLUnitCost = p1DLHrs * dlRate;
  const p1OpsOHCost  = p1DLHrs * opsOHRate;
  const p1SetupOHCost= p1SetupHrs * setupOHRate;
  const p1UnitCost   = p1M1Cost + p1M2Cost + p1DLUnitCost + p1OpsOHCost + p1SetupOHCost;

  const p2M1Cost     = m1P2Qty * m1Cost;
  const p2M2Cost     = m2P2Qty * m2Cost;
  const p2DLUnitCost = p2DLHrs * dlRate;
  const p2OpsOHCost  = p2DLHrs * opsOHRate;
  const p2SetupOHCost= p2SetupHrs * setupOHRate;
  const p2UnitCost   = p2M1Cost + p2M2Cost + p2DLUnitCost + p2OpsOHCost + p2SetupOHCost;

  const p1EndInvVal  = p1EndInv * p1UnitCost;
  const p2EndInvVal  = p2EndInv * p2UnitCost;
  const m1EndInvVal  = m1EndInv * m1Cost;
  const m2EndInvVal  = m2EndInv * m2Cost;

  // S7: COGS
  const begFGInv     = p1BegVal + p2BegVal;
  const cogm         = totalDMUsed + totalDLCost + totalOH;
  const cogsAvail    = begFGInv + cogm;
  const endFGInv     = p1EndInvVal + p2EndInvVal;
  const cogs         = cogsAvail - endFGInv;
  const grossMargin  = totalRev - cogs;

  // S8: Operating costs
  const cuFtSold     = p1Sales * p1CuFt + p2Sales * p2CuFt;
  const mktVar       = totalRev * mktPct;
  const mktTotal     = mktVar + mktFix;
  const distVarTotal = distVar * cuFtSold;
  const distTotal    = distVarTotal + distFix;
  const totalOpCosts = design + mktTotal + distTotal;

  // Operating income
  const opIncome     = grossMargin - totalOpCosts;
  const opMargin     = totalRev > 0 ? opIncome / totalRev : 0;

  // Store for Tool 2 and Tool 4
  budgetResults = {
    totalRev, p1Rev, p2Rev,
    p1Prod, p2Prod,
    totalDMUsed, m1UsedCost, m2UsedCost,
    totalDLCost, totalOH,
    cogs, grossMargin, opIncome, opMargin,
    mktPct, p1Price, p2Price, m1Cost, m2Cost,
    p1Name, p2Name, m1Name, m2Name,
  };

  // Render all schedules
  resultsEl.innerHTML = `
    <div class="budget-schedules">

      <div class="budget-schedule">
        <div class="budget-schedule__title">Schedule 1: Revenues Budget</div>
        <table class="data-table"><thead><tr><th>Product</th><th class="num">Units</th><th class="num">Price</th><th class="num">Revenue</th></tr></thead>
        <tbody>
          <tr><td>${p1Name}</td><td style="text-align:right">${p1Sales.toLocaleString()}</td><td style="text-align:right">${fmt(p1Price)}</td><td style="text-align:right">${fmt(p1Rev)}</td></tr>
          <tr><td>${p2Name}</td><td style="text-align:right">${p2Sales.toLocaleString()}</td><td style="text-align:right">${fmt(p2Price)}</td><td style="text-align:right">${fmt(p2Rev)}</td></tr>
          <tr style="font-weight:700"><td>Total</td><td></td><td></td><td style="text-align:right">${fmt(totalRev)}</td></tr>
        </tbody></table>
      </div>

      <div class="budget-schedule">
        <div class="budget-schedule__title">Schedule 2: Production Budget (units)</div>
        <table class="data-table"><thead><tr><th></th><th class="num">${p1Name}</th><th class="num">${p2Name}</th></tr></thead>
        <tbody>
          <tr><td>Budgeted Sales</td><td style="text-align:right">${p1Sales.toLocaleString()}</td><td style="text-align:right">${p2Sales.toLocaleString()}</td></tr>
          <tr><td>+ Target Ending Inventory</td><td style="text-align:right">${p1EndInv.toLocaleString()}</td><td style="text-align:right">${p2EndInv.toLocaleString()}</td></tr>
          <tr><td>− Beginning Inventory</td><td style="text-align:right">(${p1BegInv.toLocaleString()})</td><td style="text-align:right">(${p2BegInv.toLocaleString()})</td></tr>
          <tr style="font-weight:700"><td>Units to Produce</td><td style="text-align:right">${p1Prod.toLocaleString()}</td><td style="text-align:right">${p2Prod.toLocaleString()}</td></tr>
        </tbody></table>
      </div>

      <div class="budget-schedule">
        <div class="budget-schedule__title">Schedule 3A: Direct Materials Usage Budget</div>
        <table class="data-table"><thead><tr><th>Material</th><th class="num">Qty Used</th><th class="num">Cost/Unit</th><th class="num">Total Cost</th></tr></thead>
        <tbody>
          <tr><td>${m1Name} (${p1Prod.toLocaleString()} × ${m1P1Qty} + ${p2Prod.toLocaleString()} × ${m1P2Qty})</td><td style="text-align:right">${m1Total.toLocaleString()}</td><td style="text-align:right">${fmt(m1Cost)}</td><td style="text-align:right">${fmt(m1UsedCost)}</td></tr>
          <tr><td>${m2Name} (${p1Prod.toLocaleString()} × ${m2P1Qty} + ${p2Prod.toLocaleString()} × ${m2P2Qty})</td><td style="text-align:right">${m2Total.toLocaleString()}</td><td style="text-align:right">${fmt(m2Cost)}</td><td style="text-align:right">${fmt(m2UsedCost)}</td></tr>
          <tr style="font-weight:700"><td>Total DM Used</td><td></td><td></td><td style="text-align:right">${fmt(totalDMUsed)}</td></tr>
        </tbody></table>
      </div>

      <div class="budget-schedule">
        <div class="budget-schedule__title">Schedule 3B: Direct Materials Purchases Budget</div>
        <table class="data-table"><thead><tr><th>Material</th><th class="num">Used</th><th class="num">+ End Inv</th><th class="num">− Beg Inv</th><th class="num">Purchase Qty</th><th class="num">Cost</th></tr></thead>
        <tbody>
          <tr><td>${m1Name}</td><td style="text-align:right">${m1Total.toLocaleString()}</td><td style="text-align:right">${m1EndInv.toLocaleString()}</td><td style="text-align:right">(${m1BegInv.toLocaleString()})</td><td style="text-align:right">${m1PurchaseQty.toLocaleString()}</td><td style="text-align:right">${fmt(m1PurchaseCost)}</td></tr>
          <tr><td>${m2Name}</td><td style="text-align:right">${m2Total.toLocaleString()}</td><td style="text-align:right">${m2EndInv.toLocaleString()}</td><td style="text-align:right">(${m2BegInv.toLocaleString()})</td><td style="text-align:right">${m2PurchaseQty.toLocaleString()}</td><td style="text-align:right">${fmt(m2PurchaseCost)}</td></tr>
        </tbody></table>
      </div>

      <div class="budget-schedule">
        <div class="budget-schedule__title">Schedule 4: Direct Manufacturing Labor Budget</div>
        <table class="data-table"><thead><tr><th>Product</th><th class="num">Units</th><th class="num">DL-hrs/Unit</th><th class="num">Total Hours</th><th class="num">Rate</th><th class="num">Total Cost</th></tr></thead>
        <tbody>
          <tr><td>${p1Name}</td><td style="text-align:right">${p1Prod.toLocaleString()}</td><td style="text-align:right">${p1DLHrs}</td><td style="text-align:right">${p1DLHrsTotal.toLocaleString()}</td><td style="text-align:right">${fmt(dlRate)}</td><td style="text-align:right">${fmt(p1DLCost)}</td></tr>
          <tr><td>${p2Name}</td><td style="text-align:right">${p2Prod.toLocaleString()}</td><td style="text-align:right">${p2DLHrs}</td><td style="text-align:right">${p2DLHrsTotal.toLocaleString()}</td><td style="text-align:right">${fmt(dlRate)}</td><td style="text-align:right">${fmt(p2DLCost)}</td></tr>
          <tr style="font-weight:700"><td>Total</td><td></td><td></td><td style="text-align:right">${totalDLHrs.toLocaleString()}</td><td></td><td style="text-align:right">${fmt(totalDLCost)}</td></tr>
        </tbody></table>
      </div>

      <div class="budget-schedule">
        <div class="budget-schedule__title">Schedule 5: Manufacturing Overhead Budget</div>
        <table class="data-table"><thead><tr><th>Cost Pool</th><th class="num">Variable</th><th class="num">Fixed</th><th class="num">Total</th><th class="num">Rate</th></tr></thead>
        <tbody>
          <tr><td>Operations (${totalDLHrs.toLocaleString()} DL-hrs)</td><td style="text-align:right">${fmt(totalVarOH)}</td><td style="text-align:right">${fmt(fixOH)}</td><td style="text-align:right">${fmt(totalOpsOH)}</td><td style="text-align:right">${fmtDec(opsOHRate)}/DL-hr</td></tr>
          <tr><td>Setup (${totalSetupHrs.toLocaleString()} setup-hrs)</td><td style="text-align:right">${fmt(totalVarSetup)}</td><td style="text-align:right">${fmt(fixSetup)}</td><td style="text-align:right">${fmt(totalSetupOH)}</td><td style="text-align:right">${fmtDec(setupOHRate)}/setup-hr</td></tr>
          <tr style="font-weight:700"><td>Total OH</td><td></td><td></td><td style="text-align:right">${fmt(totalOH)}</td><td></td></tr>
        </tbody></table>
      </div>

      <div class="budget-schedule">
        <div class="budget-schedule__title">Schedule 6: Ending Inventories Budget</div>
        <table class="data-table"><thead><tr><th>Item</th><th class="num">Qty</th><th class="num">Unit Cost</th><th class="num">Total</th></tr></thead>
        <tbody>
          <tr><td colspan="4" style="font-weight:700;background:var(--color-gray-50);padding:var(--space-2) var(--space-4)">Direct Materials</td></tr>
          <tr><td style="padding-left:var(--space-6)">${m1Name}</td><td style="text-align:right">${m1EndInv.toLocaleString()}</td><td style="text-align:right">${fmt(m1Cost)}</td><td style="text-align:right">${fmt(m1EndInvVal)}</td></tr>
          <tr><td style="padding-left:var(--space-6)">${m2Name}</td><td style="text-align:right">${m2EndInv.toLocaleString()}</td><td style="text-align:right">${fmt(m2Cost)}</td><td style="text-align:right">${fmt(m2EndInvVal)}</td></tr>
          <tr><td colspan="4" style="font-weight:700;background:var(--color-gray-50);padding:var(--space-2) var(--space-4)">Finished Goods</td></tr>
          <tr><td style="padding-left:var(--space-6)">${p1Name}</td><td style="text-align:right">${p1EndInv.toLocaleString()}</td><td style="text-align:right">${fmtDec(p1UnitCost)}</td><td style="text-align:right">${fmt(p1EndInvVal)}</td></tr>
          <tr><td style="padding-left:var(--space-6)">${p2Name}</td><td style="text-align:right">${p2EndInv.toLocaleString()}</td><td style="text-align:right">${fmtDec(p2UnitCost)}</td><td style="text-align:right">${fmt(p2EndInvVal)}</td></tr>
          <tr style="font-weight:700"><td>Total Ending Inventory</td><td></td><td></td><td style="text-align:right">${fmt(m1EndInvVal + m2EndInvVal + p1EndInvVal + p2EndInvVal)}</td></tr>
        </tbody></table>
      </div>

      <div class="budget-schedule">
        <div class="budget-schedule__title">Schedule 7: Cost of Goods Sold Budget</div>
        <table class="data-table">
        <tbody>
          <tr><td>Beginning Finished Goods Inventory</td><td style="text-align:right">${fmt(begFGInv)}</td></tr>
          <tr><td style="padding-left:var(--space-6)">+ Direct Materials Used</td><td style="text-align:right">${fmt(totalDMUsed)}</td></tr>
          <tr><td style="padding-left:var(--space-6)">+ Direct Manufacturing Labor</td><td style="text-align:right">${fmt(totalDLCost)}</td></tr>
          <tr><td style="padding-left:var(--space-6)">+ Manufacturing Overhead</td><td style="text-align:right">${fmt(totalOH)}</td></tr>
          <tr style="font-weight:600"><td>= Cost of Goods Manufactured</td><td style="text-align:right">${fmt(cogm)}</td></tr>
          <tr style="font-weight:600"><td>Cost of Goods Available for Sale</td><td style="text-align:right">${fmt(cogsAvail)}</td></tr>
          <tr><td>− Ending Finished Goods Inventory</td><td style="text-align:right">(${fmt(endFGInv)})</td></tr>
          <tr style="font-weight:700;color:var(--color-primary)"><td>= Cost of Goods Sold</td><td style="text-align:right">${fmt(cogs)}</td></tr>
        </tbody></table>
      </div>

      <div class="budget-schedule">
        <div class="budget-schedule__title">Schedule 8: Operating Costs Budget</div>
        <table class="data-table"><thead><tr><th>Function</th><th class="num">Variable</th><th class="num">Fixed</th><th class="num">Total</th></tr></thead>
        <tbody>
          <tr><td>Product Design</td><td style="text-align:right">—</td><td style="text-align:right">${fmt(design)}</td><td style="text-align:right">${fmt(design)}</td></tr>
          <tr><td>Marketing (${(mktPct*100).toFixed(1)}% × ${fmt(totalRev)})</td><td style="text-align:right">${fmt(mktVar)}</td><td style="text-align:right">${fmt(mktFix)}</td><td style="text-align:right">${fmt(mktTotal)}</td></tr>
          <tr><td>Distribution (${cuFtSold.toLocaleString()} cu ft × ${fmt(distVar)})</td><td style="text-align:right">${fmt(distVarTotal)}</td><td style="text-align:right">${fmt(distFix)}</td><td style="text-align:right">${fmt(distTotal)}</td></tr>
          <tr style="font-weight:700"><td>Total Operating Costs</td><td></td><td></td><td style="text-align:right">${fmt(totalOpCosts)}</td></tr>
        </tbody></table>
      </div>

      <div class="budget-schedule budget-schedule--income">
        <div class="budget-schedule__title">Budgeted Income Statement</div>
        <div class="is-row"><span>Revenues</span><span>${fmt(totalRev)}</span></div>
        <div class="is-row is-row--indent"><span>Cost of Goods Sold</span><span>(${fmt(cogs)})</span></div>
        <div class="is-row is-row--subtotal"><span>Gross Margin</span><span>${fmt(grossMargin)}</span></div>
        <div class="is-row is-row--indent"><span>Operating Costs</span><span>(${fmt(totalOpCosts)})</span></div>
        <div class="is-row is-row--total ${opIncome >= 0 ? 'is-row--profit' : 'is-row--loss'}">
          <span>Operating Income</span><span>${fmt(opIncome)}</span>
        </div>
        <div class="is-row" style="font-size:var(--font-size-xs);color:var(--color-text-muted)">
          <span>Operating Margin</span><span>${fmtPct(opMargin)}</span>
        </div>
      </div>

    </div>
  `;

  const sw = getOrCreate('budget-show-work', 'div', '', resultsEl);
  renderShowWork(sw, [
    { label: 'Step 1 -- Total Revenues',          formula: 'Revenues = Sum of (Units × Price) for each product',                    values: `${fmt(p1Rev)} + ${fmt(p2Rev)}`,                         result: fmt(totalRev) },
    { label: 'Step 2 -- Units to Produce (P1)',   formula: 'Production = Sales + Target End Inv − Begin Inv',                       values: `${p1Sales.toLocaleString()} + ${p1EndInv.toLocaleString()} − ${p1BegInv.toLocaleString()}`, result: p1Prod.toLocaleString() + ' units' },
    { label: 'Step 3 -- Total DM Used',           formula: 'DM Cost = Sum of (Qty Used × Cost per Unit) for each material',         values: `${fmt(m1UsedCost)} + ${fmt(m2UsedCost)}`,               result: fmt(totalDMUsed) },
    { label: 'Step 4 -- Total DL Cost',           formula: 'DL Cost = Total DL-Hours × Wage Rate',                                  values: `${totalDLHrs.toLocaleString()} hrs × ${fmt(dlRate)}/hr`, result: fmt(totalDLCost) },
    { label: 'Step 5 -- Total Manufacturing OH',  formula: 'OH = (Var Rate × DL-hrs + Fixed) + (Setup Rate × Setup-hrs + Fixed)',   values: `${fmt(totalOpsOH)} + ${fmt(totalSetupOH)}`,             result: fmt(totalOH) },
    { label: 'Step 7 -- Cost of Goods Sold',      formula: 'COGS = Beg FG Inv + COGM − End FG Inv',                                values: `${fmt(begFGInv)} + ${fmt(cogm)} − ${fmt(endFGInv)}`,    result: fmt(cogs), highlight: true },
    { label: 'Step 9 -- Operating Income',        formula: 'Operating Income = Gross Margin − Total Operating Costs',               values: `${fmt(grossMargin)} − ${fmt(totalOpCosts)}`,            result: fmt(opIncome) + ' (' + fmtPct(opMargin) + ' margin)', highlight: true,
      note: 'The 9-step chain: Revenues → Production → DM Usage → DM Purchases → DL → Overhead → Ending Inventory → COGS → Operating Costs → Income Statement.' },
  ], { title: 'Show Work -- Operating Budget Key Calculations' });
}

// ── Tool 2: Sensitivity Analysis ─────────────────────────────

function initSensitivity() {
  const calcBtn   = document.getElementById('sens-calculate');
  const pullBtn   = document.getElementById('sens-pull-btn');
  const resultsEl = document.getElementById('sens-results');
  if (!calcBtn) return;

  pullBtn?.addEventListener('click', () => {
    if (!budgetResults) {
      alert('Run Tool 1 first to populate base case values.');
      return;
    }
    const b = budgetResults;
    const setVal = (id, val) => { const el = document.getElementById(id); if (el) el.value = val; };
    setVal('sens-p1-price',   b.p1Price);
    setVal('sens-p2-price',   b.p2Price);
    setVal('sens-m1-cost',    b.m1Cost);
    setVal('sens-m2-cost',    b.m2Cost);
    setVal('sens-base-oi',    Math.round(b.opIncome));
    setVal('sens-revenues',   Math.round(b.totalRev));
    setVal('sens-dm-total',   Math.round(b.totalDMUsed));
    setVal('sens-mkt-pct',    (b.mktPct * 100).toFixed(1));
    const p1Label = document.getElementById('sens-p1-label');
    const p2Label = document.getElementById('sens-p2-label');
    const m1Label = document.getElementById('sens-m1-label');
    const m2Label = document.getElementById('sens-m2-label');
    if (p1Label) p1Label.textContent = b.p1Name + ' Price ($)';
    if (p2Label) p2Label.textContent = b.p2Name + ' Price ($)';
    if (m1Label) m1Label.textContent = b.m1Name + ' Cost ($/unit)';
    if (m2Label) m2Label.textContent = b.m2Name + ' Cost ($/unit)';
  });

  calcBtn.addEventListener('click', () => {
    const baseP1Price  = gv('sens-p1-price');
    const baseP2Price  = gv('sens-p2-price');
    const baseM1Cost   = gv('sens-m1-cost');
    const baseM2Cost   = gv('sens-m2-cost');
    const baseOI       = gv('sens-base-oi');
    const baseRev      = gv('sens-revenues');
    const baseDM       = gv('sens-dm-total');
    const mktPct       = gv('sens-mkt-pct') / 100;

    const scenarios = [
      { label: 'Base Case',  p1Chg: 0, p2Chg: 0, m1Chg: 0, m2Chg: 0 },
      { label: 'Scenario 1', p1Chg: gv('sens-s1-p1-chg'), p2Chg: gv('sens-s1-p2-chg'), m1Chg: gv('sens-s1-m1-chg'), m2Chg: gv('sens-s1-m2-chg') },
      { label: 'Scenario 2', p1Chg: gv('sens-s2-p1-chg'), p2Chg: gv('sens-s2-p2-chg'), m1Chg: gv('sens-s2-m1-chg'), m2Chg: gv('sens-s2-m2-chg') },
    ];

    const results = scenarios.map(s => {
      const revChgPct  = (s.p1Chg + s.p2Chg) / 2 / 100;
      const newRev     = baseRev * (1 + revChgPct);
      const revDelta   = newRev - baseRev;
      const mktDelta   = revDelta * mktPct;

      const m1ChgAmt   = baseDM * (s.m1Chg / 100) * 0.5;
      const m2ChgAmt   = baseDM * (s.m2Chg / 100) * 0.5;
      const dmDelta    = m1ChgAmt + m2ChgAmt;

      const newOI      = baseOI + revDelta - mktDelta - dmDelta;
      const oiChgPct   = baseOI !== 0 ? (newOI - baseOI) / Math.abs(baseOI) : 0;

      return {...s, newRev, newOI, oiChgPct };
    });

    const el = getOrCreate('sens-results-table', 'div', '', resultsEl);
    el.innerHTML = `
      <div style="overflow-x:auto;border-radius:var(--radius-lg);border:1px solid var(--color-border);margin-top:var(--space-5)">
        <table class="data-table">
          <thead>
            <tr>
              <th>Scenario</th>
              <th class="num">P1 Price Chg</th>
              <th class="num">P2 Price Chg</th>
              <th class="num">M1 Cost Chg</th>
              <th class="num">M2 Cost Chg</th>
              <th class="num">Budgeted Revenue</th>
              <th class="num">Budgeted Op. Income</th>
              <th class="num">Change from Base</th>
            </tr>
          </thead>
          <tbody>
            ${results.map((r, i) => `
              <tr style="${i === 0 ? 'font-weight:700' : ''}${i > 0 && r.newOI < baseOI ? ';color:var(--color-danger)' : ''}">
                <td>${r.label}</td>
                <td style="text-align:right">${r.p1Chg > 0 ? '+' : ''}${r.p1Chg}%</td>
                <td style="text-align:right">${r.p2Chg > 0 ? '+' : ''}${r.p2Chg}%</td>
                <td style="text-align:right">${r.m1Chg > 0 ? '+' : ''}${r.m1Chg}%</td>
                <td style="text-align:right">${r.m2Chg > 0 ? '+' : ''}${r.m2Chg}%</td>
                <td style="text-align:right;font-family:var(--font-mono)">${fmt(r.newRev)}</td>
                <td style="text-align:right;font-family:var(--font-mono)">${fmt(r.newOI)}</td>
                <td style="text-align:right;font-family:var(--font-mono)">${i === 0 ? '—' : (r.oiChgPct >= 0 ? '+' : '') + fmtPct(r.oiChgPct)}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </div>
    `;

    const insight = getOrCreate('sens-insight', 'div', 'sensitivity-insight', resultsEl);
    const s1 = results[1];
    const s2 = results[2];
    insight.innerHTML = `
      <strong>Key insight:</strong>
      Scenario 1 changes operating income by <strong>${(s1.oiChgPct >= 0 ? '+' : '') + fmtPct(s1.oiChgPct)}</strong>
      (${fmt(s1.newOI)}).
      Scenario 2 changes operating income by <strong>${(s2.oiChgPct >= 0 ? '+' : '') + fmtPct(s2.oiChgPct)}</strong>
      (${fmt(s2.newOI)}).
      Sensitivity analysis helps managers identify which assumptions pose the greatest risk to the budget
      and develop contingency plans before the period begins.
    `;
  });
}

// ── Tool 3: Responsibility Center Classifier ──────────────────

function initRCClassifier() {
  const scenarioEl   = document.getElementById('rc-scenario');
  const feedbackEl   = document.getElementById('rc-feedback');
  const counterEl    = document.getElementById('rc-counter');
  const prevBtn      = document.getElementById('rc-prev');
  const nextBtn      = document.getElementById('rc-next');
  const progressFill = document.getElementById('rc-progress-fill');
  const progressLbl  = document.getElementById('rc-progress-label');
  if (!scenarioEl) return;

  let current = 0;
  const answers = new Array(RC_SCENARIOS.length).fill(null);
  const correct = new Array(RC_SCENARIOS.length).fill(false);

  function render(index) {
    const item = RC_SCENARIOS[index];
    scenarioEl.textContent = item.scenario;
    feedbackEl.hidden      = true;
    counterEl.textContent  = `${index + 1} of ${RC_SCENARIOS.length}`;
    prevBtn.disabled       = index === 0;

    document.querySelectorAll('.rc-btn').forEach(btn => {
      btn.classList.remove('rc-btn--correct', 'rc-btn--incorrect');
    });

    if (answers[index]) {
      const isCorrect  = answers[index] === item.answer;
      const userBtn    = document.querySelector(`.rc-btn[data-type="${answers[index]}"]`);
      const correctBtn = document.querySelector(`.rc-btn[data-type="${item.answer}"]`);
      if (userBtn)    userBtn.classList.add(isCorrect ? 'rc-btn--correct' : 'rc-btn--incorrect');
      if (!isCorrect && correctBtn) correctBtn.classList.add('rc-btn--correct');
      feedbackEl.hidden    = false;
      feedbackEl.className = `rc-feedback rc-feedback--${isCorrect ? 'success' : 'error'}`;
      feedbackEl.innerHTML = `<strong>${isCorrect ? '✓ Correct!' : '✗ Not quite.'}</strong> ${item.explanation}`;
      nextBtn.disabled     = index === RC_SCENARIOS.length - 1;
    } else {
      nextBtn.disabled = true;
    }
    updateProgress();
  }

  function updateProgress() {
    const count = correct.filter(Boolean).length;
    progressFill.style.width = `${Math.round((count / RC_SCENARIOS.length) * 100)}%`;
    progressLbl.textContent  = `${count} of ${RC_SCENARIOS.length} classified correctly`;
  }

  document.querySelectorAll('.rc-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      if (answers[current] && correct[current]) return;
      answers[current] = btn.dataset.type;
      if (btn.dataset.type === RC_SCENARIOS[current].answer) correct[current] = true;
      render(current);
    });
  });

  prevBtn.addEventListener('click', () => { if (current > 0) render(--current); });
  nextBtn.addEventListener('click', () => { if (current < RC_SCENARIOS.length - 1) render(++current); });
  render(0);
}

// ── Tool 4: Cash Budget ───────────────────────────────────────

function initCashBudget() {
  const calcBtn   = document.getElementById('cash-calculate');
  const pullBtn   = document.getElementById('cash-pull-btn');
  const resultsEl = document.getElementById('cash-results');
  if (!calcBtn) return;

  pullBtn?.addEventListener('click', () => {
    if (!budgetResults) {
      alert('Run Tool 1 first to populate revenue values.');
      return;
    }
    const rev = budgetResults.totalRev;
    const qRev = rev / 4;
    ['q1','q2','q3','q4'].forEach(q => {
      const el = document.getElementById(`cash-rev-${q}`);
      if (el) el.value = Math.round(qRev);
    });
  });

  calcBtn.addEventListener('click', () => calculateCashBudget(resultsEl));

  initRandomizer('cash-randomize', [
    { id: 'cash-begin',    min: 100000,  max: 1000000, step: 50000, integer: true },
    { id: 'cash-min',      min: 50000,   max: 500000,  step: 25000, integer: true },
    { id: 'cash-same-pct', min: 50,      max: 90,      step: 5,     integer: true },
    { id: 'cash-rev-q1',   min: 5000000, max: 20000000,step: 500000,integer: true },
    { id: 'cash-rev-q2',   min: 5000000, max: 20000000,step: 500000,integer: true },
    { id: 'cash-rev-q3',   min: 5000000, max: 20000000,step: 500000,integer: true },
    { id: 'cash-rev-q4',   min: 5000000, max: 20000000,step: 500000,integer: true },
  ], () => calculateCashBudget(resultsEl));
}

function calculateCashBudget(resultsEl) {
  const beginCash  = gv('cash-begin');
  const minBalance = gv('cash-min');
  const annualRate = gv('cash-rate') / 100;
  const samePct    = gv('cash-same-pct') / 100;
  const nextPct    = gv('cash-next-pct') / 100;
  const begAR      = gv('cash-beg-ar');

  const revenues   = ['q1','q2','q3','q4'].map(q => gv(`cash-rev-${q}`));
  const disbCats   = ['dm','dl','oh','op','cap','tax'];
  const disbLabels = ['Direct Materials','Direct Labor','Mfg Overhead','Operating Costs','Capital Expenditures','Income Taxes'];

  const disb = disbCats.map(cat =>
    ['q1','q2','q3','q4'].map(q => gv(`cash-${cat}-${q}`))
  );

  // Collections
  const collections = [0,0,0,0];
  collections[0] = begAR + revenues[0] * samePct;
  collections[1] = revenues[0] * nextPct + revenues[1] * samePct;
  collections[2] = revenues[1] * nextPct + revenues[2] * samePct;
  collections[3] = revenues[2] * nextPct + revenues[3] * samePct;
  const endingAR   = revenues[3] * nextPct;

  const quarters = [];
  let cumLoan    = 0;
  let cashBal    = beginCash;

  for (let q = 0; q < 4; q++) {
    const totalDisb    = disbCats.reduce((s, _, i) => s + disb[i][q], 0);
    const totalAvail   = cashBal + collections[q];
    const totalNeeded  = totalDisb + minBalance;
    const surplus      = totalAvail - totalNeeded;

    let borrow = 0, repay = 0, interest = 0;

    if (surplus < 0) {
      borrow   = Math.ceil(Math.abs(surplus) / 1000) * 1000;
      cumLoan += borrow;
    } else if (cumLoan > 0) {
      repay    = Math.min(surplus, cumLoan);
      repay    = Math.floor(repay / 1000) * 1000;
      interest = repay * (annualRate * 0.25);
      cumLoan -= repay;
    }

    const endCash = totalAvail - totalDisb + borrow - repay - interest;
    cashBal       = endCash;

    quarters.push({
      q: q + 1,
      collections: collections[q],
      totalAvail,
      totalDisb,
      surplus,
      borrow,
      repay,
      interest,
      endCash,
      disbByCategory: disbCats.map((_, i) => disb[i][q]),
    });
  }

  const totalCollections = quarters.reduce((s, q) => s + q.collections, 0);
  const totalDisb        = quarters.reduce((s, q) => s + q.totalDisb, 0);
  const totalBorrow      = quarters.reduce((s, q) => s + q.borrow, 0);
  const totalRepay       = quarters.reduce((s, q) => s + q.repay, 0);
  const totalInterest    = quarters.reduce((s, q) => s + q.interest, 0);

  const tableHTML = `
    <div style="overflow-x:auto;border-radius:var(--radius-lg);border:1px solid var(--color-border);margin-top:var(--space-5)">
      <table class="data-table cash-budget-table">
        <thead>
          <tr>
            <th>Item</th>
            <th class="num">Q1</th>
            <th class="num">Q2</th>
            <th class="num">Q3</th>
            <th class="num">Q4</th>
            <th class="num">Year Total</th>
          </tr>
        </thead>
        <tbody>
          <tr style="font-weight:600;background:var(--color-gray-50)"><td>Beginning Cash Balance</td>
            <td style="text-align:right">${fmt(beginCash)}</td>
            ${quarters.slice(1).map(q => `<td style="text-align:right">${fmt(quarters[q.q-2].endCash)}</td>`).join('')}
            <td style="text-align:right">${fmt(beginCash)}</td>
          </tr>
          <tr><td>+ Collections from Customers</td>
            ${quarters.map(q => `<td style="text-align:right">${fmt(q.collections)}</td>`).join('')}
            <td style="text-align:right">${fmt(totalCollections)}</td>
          </tr>
          <tr style="font-weight:600"><td>= Total Cash Available</td>
            ${quarters.map(q => `<td style="text-align:right">${fmt(q.totalAvail)}</td>`).join('')}
            <td></td>
          </tr>
          <tr style="background:var(--color-gray-50)"><td colspan="6" style="font-weight:700;padding:var(--space-2) var(--space-4)">Disbursements</td></tr>
          ${disbLabels.map((label, i) => `
            <tr><td style="padding-left:var(--space-6)">${label}</td>
              ${quarters.map(q => `<td style="text-align:right">${fmt(q.disbByCategory[i])}</td>`).join('')}
              <td style="text-align:right">${fmt(quarters.reduce((s,q) => s + q.disbByCategory[i], 0))}</td>
            </tr>
          `).join('')}
          <tr style="font-weight:600"><td>= Total Disbursements</td>
            ${quarters.map(q => `<td style="text-align:right">(${fmt(q.totalDisb)})</td>`).join('')}
            <td style="text-align:right">(${fmt(totalDisb)})</td>
          </tr>
          <tr><td>Minimum Cash Balance Required</td>
            ${quarters.map(() => `<td style="text-align:right">(${fmt(minBalance)})</td>`).join('')}
            <td></td>
          </tr>
          <tr style="font-weight:600"><td>Cash Surplus / (Deficiency)</td>
            ${quarters.map(q => `<td style="text-align:right;color:${q.surplus < 0 ? 'var(--color-danger)' : 'var(--color-success)'}">${fmt(q.surplus)}</td>`).join('')}
            <td></td>
          </tr>
          <tr style="background:var(--color-gray-50)"><td colspan="6" style="font-weight:700;padding:var(--space-2) var(--space-4)">Financing</td></tr>
          <tr><td style="padding-left:var(--space-6)">Borrowing (beginning of quarter)</td>
            ${quarters.map(q => `<td style="text-align:right;color:${q.borrow > 0 ? 'var(--color-danger)' : ''}">${q.borrow > 0 ? fmt(q.borrow) : '—'}</td>`).join('')}
            <td style="text-align:right">${totalBorrow > 0 ? fmt(totalBorrow) : '—'}</td>
          </tr>
          <tr><td style="padding-left:var(--space-6)">Repayment (end of quarter)</td>
            ${quarters.map(q => `<td style="text-align:right;color:${q.repay > 0 ? 'var(--color-success)' : ''}">${q.repay > 0 ? '(' + fmt(q.repay) + ')' : '—'}</td>`).join('')}
            <td style="text-align:right">${totalRepay > 0 ? '(' + fmt(totalRepay) + ')' : '—'}</td>
          </tr>
          <tr><td style="padding-left:var(--space-6)">Interest Paid</td>
            ${quarters.map(q => `<td style="text-align:right">${q.interest > 0 ? '(' + fmt(q.interest) + ')' : '—'}</td>`).join('')}
            <td style="text-align:right">${totalInterest > 0 ? '(' + fmt(totalInterest) + ')' : '—'}</td>
          </tr>
          <tr style="font-weight:700;color:var(--color-primary)"><td>Ending Cash Balance</td>
            ${quarters.map(q => `<td style="text-align:right">${fmt(q.endCash)}</td>`).join('')}
            <td style="text-align:right">${fmt(quarters[3].endCash)}</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="sensitivity-insight" style="margin-top:var(--space-4)">
      <strong>Ending Accounts Receivable:</strong> ${fmt(endingAR)} (${(nextPct*100).toFixed(0)}% of Q4 revenues uncollected).
      ${totalBorrow > 0 ? `<strong>Total borrowed:</strong> ${fmt(totalBorrow)}. Total interest: ${fmt(totalInterest)}. This is a self-liquidating loan -- cash from operations repays it.` : '<strong>No borrowing required</strong> -- cash flows are sufficient to maintain the minimum balance each quarter.'}
    </div>
  `;

  resultsEl.innerHTML = tableHTML;

  const sw = getOrCreate('cash-show-work', 'div', '', resultsEl);
  renderShowWork(sw, [
    {
      label:   'Q1 Collections',
      formula: 'Collections = Beginning AR + (Q1 Revenue × Same-Quarter %)',
      values:  `${fmt(begAR)} + (${fmt(revenues[0])} × ${(samePct*100).toFixed(0)}%)`,
      result:  fmt(collections[0]),
    },
    {
      label:   'Q2 Collections',
      formula: 'Collections = (Q1 Revenue × Next-Quarter %) + (Q2 Revenue × Same-Quarter %)',
      values:  `(${fmt(revenues[0])} × ${(nextPct*100).toFixed(0)}%) + (${fmt(revenues[1])} × ${(samePct*100).toFixed(0)}%)`,
      result:  fmt(collections[1]),
    },
    {
      label:   'Q1 Cash Position',
      formula: 'Surplus = Total Available − Total Disbursements − Minimum Balance',
      values:  `${fmt(quarters[0].totalAvail)} − ${fmt(quarters[0].totalDisb)} − ${fmt(minBalance)}`,
      result:  fmt(quarters[0].surplus),
      highlight: quarters[0].surplus < 0,
      note:    quarters[0].surplus < 0 ? 'Deficiency -- borrowing required at the start of Q1.' : 'Surplus -- no borrowing needed in Q1.',
    },
    {
      label:   'Ending AR (Year-End)',
      formula: 'Ending AR = Q4 Revenue × Next-Quarter Collection %',
      values:  `${fmt(revenues[3])} × ${(nextPct*100).toFixed(0)}%`,
      result:  fmt(endingAR),
      note:    'This appears as Accounts Receivable on the budgeted balance sheet.',
    },
  ], { title: 'Show Work -- Cash Budget Key Calculations' });
}

// ── Tool 5: Kaizen Budget Simulator ──────────────────────────

function initKaizen() {
  const calcBtn   = document.getElementById('kaizen-calculate');
  const resultsEl = document.getElementById('kaizen-results');
  if (!calcBtn) return;

  calcBtn.addEventListener('click', () => calculateKaizen(resultsEl));

  initRandomizer('kaizen-randomize', [
    { id: 'kz-base-rate',    min: 5,      max: 100,    step: 1,    integer: false },
    { id: 'kz-base-qty',     min: 10000,  max: 500000, step: 10000,integer: true },
    { id: 'kz-improve-pct',  min: 0.5,    max: 5,      step: 0.25, integer: false },
    { id: 'kz-periods',      min: 2,      max: 8,      step: 1,    integer: true },
    { id: 'kz-target-rate',  min: 1,      max: 90,     step: 1,    integer: false },
  ], () => calculateKaizen(resultsEl));
}

function calculateKaizen(resultsEl) {
  const activity    = gs('kz-activity') || 'Activity';
  const driver      = gs('kz-driver')   || 'units';
  const baseRate    = gv('kz-base-rate');
  const baseQty     = gv('kz-base-qty');
  const improvePct  = gv('kz-improve-pct') / 100;
  const periods     = Math.round(gv('kz-periods'));
  const targetRate  = gv('kz-target-rate');

  const schedule = [];
  let rate = baseRate;
  const baseCost = baseRate * baseQty;

  for (let p = 1; p <= periods; p++) {
    if (p > 1) rate = rate * (1 - improvePct);
    const totalCost       = rate * baseQty;
    const savingsVsBase   = baseCost - totalCost;
    const savingsVsPrior  = p === 1 ? 0 : schedule[p-2].totalCost - totalCost;
    const cumSavings      = baseCost * p - schedule.slice(0, p-1).reduce((s, r) => s + r.totalCost, 0) - totalCost;
    schedule.push({ period: p, rate, totalCost, savingsVsBase, savingsVsPrior, cumSavings });
  }

  const targetMet = targetRate > 0 ? schedule.find(s => s.rate <= targetRate) : null;
  const finalRate = schedule[schedule.length - 1].rate;
  const totalSavings = schedule.reduce((s, r) => s + r.savingsVsBase, 0);

  const svgW = 500;
  const svgH = 160;
  const padL = 70, padR = 20, padT = 20, padB = 30;
  const chartW = svgW - padL - padR;
  const chartH = svgH - padT - padB;
  const maxCost = baseCost * 1.05;
  const barW    = chartW / periods * 0.6;
  const barGap  = chartW / periods;

  let svgBars = '';
  schedule.forEach((s, i) => {
    const barH  = (s.totalCost / maxCost) * chartH;
    const x     = padL + i * barGap + (barGap - barW) / 2;
    const y     = padT + chartH - barH;
    const color = targetRate > 0 && s.rate <= targetRate ? 'var(--color-success)' : 'var(--color-primary)';
    svgBars += `<rect x="${x}" y="${y}" width="${barW}" height="${barH}" fill="${color}" opacity="0.8" rx="2"/>`;
    svgBars += `<text x="${x + barW/2}" y="${svgH - padB + 14}" text-anchor="middle" font-size="10" fill="var(--color-text-muted)">P${s.period}</text>`;
    svgBars += `<text x="${x + barW/2}" y="${y - 4}" text-anchor="middle" font-size="9" fill="var(--color-text-muted)">${fmt(s.totalCost)}</text>`;
  });

  let targetLine = '';
  if (targetRate > 0) {
    const targetCost = targetRate * baseQty;
    const ty = padT + chartH - (targetCost / maxCost) * chartH;
    targetLine = `<line x1="${padL}" y1="${ty}" x2="${padL + chartW}" y2="${ty}" stroke="var(--color-success)" stroke-width="1.5" stroke-dasharray="5,3"/>`;
    targetLine += `<text x="${padL + chartW - 4}" y="${ty - 4}" text-anchor="end" font-size="9" fill="var(--color-success)">Target: ${fmt(targetRate)}/unit</text>`;
  }

  const yTicks = [0, 0.25, 0.5, 0.75, 1].map(t => {
    const cost = maxCost * t;
    const y    = padT + chartH - t * chartH;
    return `<text x="${padL - 6}" y="${y + 4}" text-anchor="end" font-size="9" fill="var(--color-text-muted)">${fmt(cost)}</text>
            <line x1="${padL}" y1="${y}" x2="${padL + chartW}" y2="${y}" stroke="var(--color-gray-100)" stroke-width="1"/>`;
  }).join('');

  const svg = `<svg viewBox="0 0 ${svgW} ${svgH}" style="width:100%;height:${svgH}px">
    ${yTicks}
    <line x1="${padL}" y1="${padT}" x2="${padL}" y2="${padT+chartH}" stroke="var(--color-gray-300)" stroke-width="1.5"/>
    <line x1="${padL}" y1="${padT+chartH}" x2="${padL+chartW}" y2="${padT+chartH}" stroke="var(--color-gray-300)" stroke-width="1.5"/>
    ${targetLine}
    ${svgBars}
  </svg>`;

  resultsEl.innerHTML = `
    <div class="kaizen-chart" style="margin-top:var(--space-5)">${svg}</div>
    <div style="overflow-x:auto;border-radius:var(--radius-lg);border:1px solid var(--color-border);margin-top:var(--space-4)">
      <table class="data-table">
        <thead>
          <tr>
            <th>Period</th>
            <th class="num">Rate ($/unit)</th>
            <th class="num">Total Cost</th>
            <th class="num">Savings vs Base</th>
            <th class="num">Savings vs Prior</th>
            <th class="num">Cumulative Savings</th>
          </tr>
        </thead>
        <tbody>
          <tr style="background:var(--color-gray-50);font-weight:600">
            <td>Base</td>
            <td style="text-align:right;font-family:var(--font-mono)">${fmtDec(baseRate)}</td>
            <td style="text-align:right;font-family:var(--font-mono)">${fmt(baseCost)}</td>
            <td style="text-align:right">—</td>
            <td style="text-align:right">—</td>
            <td style="text-align:right">—</td>
          </tr>
          ${schedule.map(s => `
            <tr style="${targetRate > 0 && s.rate <= targetRate ? 'color:var(--color-success);font-weight:600' : ''}">
              <td>Period ${s.period}${targetRate > 0 && s.rate <= targetRate && (!schedule[s.period-2] || schedule[s.period-2].rate > targetRate) ? ' ✓ Target Met' : ''}</td>
              <td style="text-align:right;font-family:var(--font-mono)">${fmtDec(s.rate)}</td>
              <td style="text-align:right;font-family:var(--font-mono)">${fmt(s.totalCost)}</td>
              <td style="text-align:right;font-family:var(--font-mono);color:var(--color-success)">${fmt(s.savingsVsBase)}</td>
              <td style="text-align:right;font-family:var(--font-mono);color:var(--color-success)">${s.period === 1 ? '—' : fmt(s.savingsVsPrior)}</td>
              <td style="text-align:right;font-family:var(--font-mono)">${fmt(s.cumSavings)}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>
    <div class="sensitivity-insight" style="margin-top:var(--space-4)">
      <strong>${activity}:</strong> Starting at ${fmtDec(baseRate)}/${driver}, a ${(improvePct*100).toFixed(2)}% improvement per period
      reduces the rate to ${fmtDec(finalRate)}/${driver} by Period ${periods} --
      a ${fmtPct((baseRate - finalRate) / baseRate)} total reduction.
      Total savings over ${periods} periods: <strong>${fmt(totalSavings)}</strong>.
      ${targetMet ? `Target rate of ${fmtDec(targetRate)}/${driver} is <strong style="color:var(--color-success)">achieved in Period ${targetMet.period}</strong>.` : targetRate > 0 ? `Target rate of ${fmtDec(targetRate)}/${driver} is <strong style="color:var(--color-danger)">not reached</strong> within ${periods} periods.` : ''}
    </div>
  `;

  const sw = getOrCreate('kaizen-show-work', 'div', '', resultsEl);
  renderShowWork(sw, [
    {
      label:   'Period 1 Rate',
      formula: 'Rate = Base Rate (no improvement in first period)',
      values:  `${fmtDec(baseRate)}/${driver}`,
      result:  fmtDec(schedule[0].rate) + '/' + driver,
    },
    {
      label:   'Period 2 Rate',
      formula: 'Rate = Prior Rate × (1 − Improvement %)',
      values:  `${fmtDec(schedule[0].rate)} × (1 − ${(improvePct*100).toFixed(2)}%)`,
      result:  fmtDec(schedule[1]?.rate || 0) + '/' + driver,
    },
    {
      label:   `Period ${periods} Rate`,
      formula: 'Rate = Base Rate × (1 − Improvement %)^(Periods − 1)',
      values:  `${fmtDec(baseRate)} × (1 − ${(improvePct*100).toFixed(2)}%)^${periods - 1}`,
      result:  fmtDec(finalRate) + '/' + driver,
      highlight: true,
    },
    {
      label:   'Total Savings',
      formula: 'Total Savings = Sum of (Base Cost − Period Cost) for each period',
      values:  `${periods} periods × average savings per period`,
      result:  fmt(totalSavings),
      highlight: true,
      note:    'Kaizen budgeting motivates continuous small improvements rather than one-time cost cuts. The cumulative effect compounds over time.',
    },
  ], { title: 'Show Work -- Kaizen Budget Calculations' });
}

// ── Key Terms ─────────────────────────────────────────────────

function initKeyTerms() {
  const grid = document.getElementById('key-terms-grid');
  if (!grid) return;
  KEY_TERMS.forEach(item => {
    const div = document.createElement('div');
    div.className = 'key-term';
    div.setAttribute('role', 'button');
    div.setAttribute('tabindex', '0');
    div.setAttribute('aria-expanded', 'false');
    div.innerHTML = `<div class="key-term__word">${item.term}</div><p class="key-term__definition">${item.definition}</p>`;
    div.addEventListener('click', () => {
      const open = div.classList.toggle('key-term--open');
      div.setAttribute('aria-expanded', open);
    });
    div.addEventListener('keydown', e => {
      if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); div.click(); }
    });
    grid.appendChild(div);
  });
}

// ── Chapter Complete ──────────────────────────────────────────

function initChapterComplete() {
  const btn       = document.getElementById('mark-complete-btn');
  const statusEl  = document.getElementById('ch06-status');
  const actionsEl = btn?.closest('.chapter-complete__actions');
  if (isChapterComplete('ch06')) setCompleteUI();
  btn?.addEventListener('click', () => { markChapterComplete('ch06'); setCompleteUI(); });
  function setCompleteUI() {
    if (statusEl) { statusEl.textContent = '✓ Completed'; statusEl.classList.add('chapter-hero__progress-label--complete'); }
    if (btn)      { btn.textContent = '✓ Completed'; btn.disabled = true; }
    if (actionsEl && !actionsEl.querySelector('.reset-chapter-btn')) {
      const resetBtn = document.createElement('button');
      resetBtn.className = 'btn btn--ghost-danger reset-chapter-btn';
      resetBtn.textContent = 'Reset Chapter';
      resetBtn.addEventListener('click', () => {
        if (confirm('Reset Chapter 6? This will clear your completion status and reload the page.')) {
          resetChapter('ch06');
          window.location.reload();
        }
      });
      actionsEl.appendChild(resetBtn);
    }
  }
}

// ── Init ──────────────────────────────────────────────────────

document.addEventListener('DOMContentLoaded', () => {
  initBudgetBuilder();
  initSensitivity();
  initRCClassifier();
  initCashBudget();
  initKaizen();
  initKeyTerms();
  initChapterComplete();
});
